# Generated by Django 3.0.9 on 2020-08-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydbapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credential',
        ),
    ]
